Import library
```{r, message=FALSE, warning=FALSE}
source(paste(getwd(),"/helper_functions/all_helper.r",sep = ""), chdir = T)
import_all_library()
```

```{r}
lang="English"
item_data<-get_lang_item_data(lang = lang,lang_form = "WS",lex_class = "nouns") %>% trim_unilemma()
admin_data<-get_lang_admin_data(lang = lang, lang_form = "WS")
instr_data<-get_lang_instr_data(lang = lang,lang_form = "WS")
item_data
admin_data 
```

```{r}
word_aoa<-get_lang_aoa(lang_item = item_data, admin_data = admin_data, instr_data = instr_data)
word_aoa
aoa_frame<-make_aoa_dataframe(lang = lang, lang_form = "WS", lex_class = "nouns") %>% 
  trim_unilemma()
aoa_frame
semantic_feature<- get_McRae(words_list = item_data) %>% McRae_threshold(threshold = 1)
semantic_feature
```

```{r}
McRae_PAT<- PAT_generator(semantic_feature = semantic_feature, vocab_month = aoa_frame)
write_out_csv(aoa_frame, lang = lang, type = "McRae_PAT")
McRae_PAT
```
```{r}
McRae_PAC<- PAC_generator(vocab_month = aoa_frame, pairs = semantic_feature )
McRae_PAC
write_out_csv(var = McRae_PAC, lang = lang, type = "McRae_PAC")
```

```{r}
assoc_pairs<- make_assoc_pairs(lemma_list = item_data)
assoc_pairs
```

```{r}
assoc_PAT<- PAT_generator(vocab_month = aoa_frame, semantic_feature = assoc_pairs)
assoc_PAT
write_out_csv(var = assoc_PAT, lang = lang, type =  "assoc_PAT")
```
```{r}
assoc_PAC<- PAC_generator(vocab_month = aoa_frame, pairs = assoc_pairs)
write_out_csv(var = assoc_PAC, lang = lang, type = "assoc_PAC")
```


```{r}
PAT_generator(vocab_month = aoa_frame, semantic_feature = semantic_feature)
```

```{r, message=FALSE, warning=FALSE}
langs<- c("English","Korean", "Russian", "Danish", "Italian", "Spanish", "Croatian","Norwegian")
for (lang in langs){
print(lang)
item_data<-get_lang_item_data(lang = lang,lang_form = "WS",lex_class = "nouns") %>% trim_unilemma()
# admin_data<-get_lang_admin_data(lang = lang, lang_form = "WS")
# instr_data<-get_lang_instr_data(lang = lang,lang_form = "WS")
# 
# word_aoa<-get_lang_aoa(lang_item = item_data, admin_data = admin_data, instr_data = instr_data)

aoa_frame<-make_aoa_dataframe(lang = lang, lang_form = "WS", lex_class = "nouns") %>% 
  trim_unilemma()

semantic_feature<- get_McRae(words_list = item_data) %>% McRae_threshold(threshold = 1)



# McRae_PAT<- PAT_generator(vocab_month = aoa_frame, semantic_feature = semantic_feature)
# write_out_csv(var = McRae_PAT, lang = lang, type = "McRae_PAT")

McRae_PAC<- PAC_generator(vocab_month = aoa_frame, pairs = semantic_feature )
write_out_csv(var = McRae_PAC, lang = lang, type = "McRae_PAC_od")


assoc_pairs<- make_assoc_pairs(lemma_list = item_data)

# assoc_PAT<- PAT_generator(vocab_month = aoa_frame, semantic_feature = assoc_pairs)
# write_out_csv(var = assoc_PAT, lang = lang, type =  "assoc_PAT")

assoc_PAC<- PAC_generator(vocab_month = aoa_frame, pairs = assoc_pairs)
write_out_csv(var = assoc_PAC, lang = lang, type = "assoc_PAC_od")
}

```

```{r, message=FALSE, warning=FALSE}
lang="English"
aoa_frame<-make_aoa_dataframe(lang = lang, lang_form = "WS", lex_class = "nouns")
aoa_frame
threshold<- c(1,2,3,4)
phono_dist<- read.csv(paste(getwd(), "/out_files/",lang, "_IPA.csv", sep = "")) %>% filter(uni_lemma %in% aoa_frame$unilemma)

for (t in threshold){
  print(t)
  phono_pair<- phono_dist %>% mutate(link=as.numeric(phono.dist<=t)) %>% select(-phono.dist)
  phono_PAC<-PAC_generator(vocab_month = aoa_frame, pairs = phono_pair)
  write_out_csv(var = phono_PAC, lang = "English", type = paste("PAC_at", t, sep = ""))
  phono_PAT<-PAT_generator(vocab_month = aoa_frame, semantic_feature = phono_pair)
  write_out_csv(var = phono_PAT, lang = "English", type = paste("PAT_at", t, sep = ""))
}



```
```{r}
langs<- c("English", "Korean", "Russian", "Danish", "Italian", "Spanish", "Croatian","Norwegian")
for (lang in langs){
  print(lang)
w2v<- read.csv(paste(getwd(),"/in_files/w2v_pair.csv", sep = ""))
aoa_frame<- make_aoa_dataframe(lang = lang)
lemma_list <- aoa_frame %>% filter(month==aoa_frame$month[1]) %>% trim_all_unilemma() %>% select(item, uni_lemma) %>% rename(definition=uni_lemma)

w2v<- w2v %>% 
  filter(item.definition %in% lemma_list$definition, 
         pair.definition %in% lemma_list$definition, 
         item.definition!=pair.definition) %>%
  left_join(lemma_list %>% rename(item.definition=definition)) %>%
  left_join((lemma_list %>% rename(pair=item, pair.definition=definition))) %>%
  mutate(link=sim)

w2v_PAC<- PAC_generator(vocab_month = aoa_frame, pairs = w2v)
write_out_csv(var = w2v_PAC, lang = lang, type = "w2v_PAC")
  w2v_PAT<- PAT_generator(vocab_month = aoa_frame, semantic_feature = w2v)
write_out_csv(var = w2v_PAT, lang = lang, type = "w2v_PAT")
}
```

```{r}
w2v %>% filter(link==1)
```


```{r}
aoa_frame<- make_aoa_dataframe(lang = "English") %>% trim_unilemma()
lemma_list<- aoa_frame %>% select(uni_lemma) %>% unique()
lemma_list
assoc_pairs<- make_assoc_pairs(lemma_list = lemma_list)
McRae_pairs<- get_McRae(words_list = aoa_frame)
assoc_pairs
McRae_pairs
```

```{r}
assoc_pairs %>% filter((item %in% McRae_pairs$item) | (item %in% McRae_pairs$pair))
```


```{r, message=FALSE, warning=FALSE}
langs<- c("English", "Korean") #, "Russian", "Danish", "Italian", "Spanish", "Croatian","Norwegian")
for (lang in langs){
  print(lang)
item_data<-get_lang_item_data(lang = lang,lang_form = "WS",lex_class = "nouns") %>% trim_unilemma()
# admin_data<-get_lang_admin_data(lang = lang, lang_form = "WS")
# instr_data<-get_lang_instr_data(lang = lang,lang_form = "WS")
# 
# word_aoa<-get_lang_aoa(lang_item = item_data, admin_data = admin_data, instr_data = instr_data)

aoa_frame<-make_aoa_dataframe(lang = lang, lang_form = "WS", lex_class = "nouns") %>% 
  trim_unilemma()
aoa_frame

semantic_feature<- get_McRae(words_list = item_data) %>% McRae_threshold(threshold = 1)



McRae_PAT<- PAT_generator(vocab_month = aoa_frame, semantic_feature = semantic_feature)
write_out_csv(var = McRae_PAT, lang = lang, type = "McRae_PAT")

McRae_PAC<- PAC_generator(vocab_month = aoa_frame, pairs = semantic_feature )
write_out_csv(var = McRae_PAC, lang = lang, type = "McRae_PAC_od")


assoc_pairs<- make_assoc_pairs(lemma_list = item_data)
assoc_pairs
assoc_PAT<- PAT_generator(vocab_month = aoa_frame, semantic_feature = assoc_pairs)
write_out_csv(var = assoc_PAT, lang = lang, type =  "assoc_PAT")

assoc_PAC<- PAC_generator(vocab_month = aoa_frame, pairs = assoc_pairs)
write_out_csv(var = assoc_PAC, lang = lang, type = "assoc_PAC")
assoc_PAC

# assoc_PAC_od<- PAC_generator_od(vocab_month = aoa_frame, pairs = assoc_pairs)
# write_out_csv(var = assoc_PAC_od, lang = lang, type = "assoc_PAC_od")
}
```

```{r}
get_item_data(language = "Mandarin",form = "WS") %>% filter(type=="word", lexical_class=="nouns") %>% select(num_item_id, definition, uni_lemma)
```
```{r}
write_out_csv(var = PAC, lang = "English", type = "PAC_corrected")
```

```{r}
assoc_PAC<- PAC
lm_PAC<- assoc_PAC %>% filter(learned==1) %>%  select(month,value) 

growth_value<-lm_PAC$value
month<-lm_PAC$month
paclm<-lm(growth_value ~ month)
summary(paclm)


ggplot(lm_PAC , aes(x=month, y=growth_value))+
  geom_point(alpha=1/2, position = position_jitter(h=0))+
  scale_y_continuous(breaks = seq(0,40, by=10))+
  scale_x_continuous(breaks = seq(16,30, by=1))+
  geom_smooth(method = "lm", se = FALSE)
```
```{bash}

word= speak -q --ipa cat
```

```{r}
lang="fr"
a<- system(paste("speak -q -v ", lang, " --ipa cat"), intern=T)
a
```
```{r}
source("all_helper.r")
parent_freq <- read.csv(paste(getwd(),"/in_files/parent_freq.csv", sep = ""), as.is = T)
langs<- c("English (American)") #, "Spanish", "Croatian", "Italian", "Danish", "Norwegian", "Turkish")
abbr <- c("en-us")#, "es", "hr", "it", "da", "no", "tr")
#for (lang in langs){
lang="English (American)"
  lang_abbr<- abbr[which(langs==lang)]
  IPA_items<- get_item_data(language = lang, form = "WS") %>% 
    select(num_item_id, definition, uni_lemma, type) %>%
    rename(item=num_item_id) %>%
    filter(type =="word") %>% 
    trim_all_definition() %>% 
    rowwise() %>%
    mutate(IPA= Speak(lang=lang, word=definition))

  item_IPA_join <- IPA_items %>% select(item, IPA)
  only_IPA <- IPA_items %>% select(IPA)
  item_IPA_join
  only_IPA
  IPA_pairs <- expand.grid(only_IPA$IPA, only_IPA$IPA) %>%
    left_join(item_IPA_join, by = c("Var1" = "IPA"))  %>%
    rename(pair = item, pair.definition = Var1) %>%
    left_join(item_IPA_join, by = c("Var2" = "IPA")) %>%
    rename(item.definition = Var2) %>%
    rowwise() %>%
    mutate(dist = adist(item.definition, pair.definition)) %>%
    select(item, item.definition, pair, pair.definition, dist)
  
#  aoa_frame<- make_aoa_dataframe(lang = "English")
#  phono_PAC<- PAC_generator(vocab_month = aoa_frame, pairs = IPA_pairs %>% rename(link=dist))
#  write_out_csv(var = IPA_items, lang = lang, type = "IPA")
#}
IPA_pairs
```

```{r}
aoa_frame<- make_aoa_dataframe(lang = lang) %>% filter(definition %in% parent_freq$definition)
aoa_frame
IPA_pairs
#phono_PAC<- PAC_generator_phono(vocab_month = aoa_frame, pairs = IPA_pairs %>% mutate(as.numeric(link=dist<=2)))
#phono_PAC
```
```{r}

IPA_pairs_thresholded<- IPA_pairs %>% mutate(link=as.numeric(dist<=2)) %>% filter(item!=pair) 
phono_PAC<- PAC_generator_phono(vocab_month = aoa_frame, pairs = IPA_pairs_thresholded)
phono_PAC


```

```{r}

assoc_PAC<- phono_PAC %>% 
   trim_all_definition() %>%
   rowwise() %>%
   mutate(IPA=Speak(lang =lang,word = definition))
assoc_PAC
```

```{r}
PAC<- assoc_PAC %>% 
  mutate(IPA=gsub(" ","", IPA)) %>% 
  mutate(length=str_count(IPA)) %>%
  left_join(parent_freq) %>%
  mutate(freq=as.numeric(freq))
  
  
lm_PAC<- PAC %>% filter(learned==1) %>%  select(month, value, length, freq)

degree<-lm_PAC$value
month<-lm_PAC$month
length<-lm_PAC$length
freq<- lm_PAC$freq

monthlm<- lm(degree ~ month)
summary(monthlm)$r.squared
BIC(monthlm)

freqlm<-lm(degree ~ freq + month)
summary(paclm)$r.squared
BIC(freqlm)

lenlm<- lm(degree ~ length +month)
summary(lenlm)$r.squared
BIC(lenlm)

PAClm<-lm(degree ~ length)
summary(PAClm)
BIC(PAClm)
# ggplot(lm_PAC , aes(x=month, y=degree))+
#   geom_point(alpha=1/2, position = position_jitter(h=0))+
#   scale_y_continuous(breaks = seq(0,20, by=1))+
#   scale_x_continuous(breaks = seq(16,30, by=1))+
#   geom_smooth(method = "lm", se = FALSE) +
#   ggtitle(label = "PAC degree; T<=2")


```

```{r}
parent_freq <- read.csv(paste(getwd(),"/in_files/parent_freq.csv", sep = ""), as.is = T)
PAC<- assoc_PAC %>% 
  mutate(IPA=gsub(" ","", IPA)) %>% 
  mutate(length=str_count(IPA)) %>%
  left_join(parent_freq) %>%
  filter(!is.na(freq)) %>%
  mutate(freq=as.numeric(freq))
PAC
```

