```{r, message=FALSE, warning=FALSE}
source(paste(getwd(),"/helper_functions/all_helper.r",sep = ""), chdir = T)
import_all_library()
```

```{r}
parent_freq<- read.csv(paste(getwd(),"/in_files/log_freq.csv", sep = ""), as.is = T) 
parent_freq
PAC_frame<- make_aoa_dataframe(lang = "English (American)") %>%
  #trim_all_definition() %>%
  filter(definition %in% parent_freq$definition)

lemmalist<- PAC_frame %>% filter(month==16) %>% select(item, uni_lemma)

assoc_pairs<- make_assoc_pairs(lemma_list = lemmalist)
assoc_PAC<- PAC_generator(vocab_month = PAC_frame, word_pairs =  assoc_pairs) %>%
  left_join(parent_freq) %>%
  rename(value2=freq) %>%
  mutate(value2=as.numeric(value2))

write_out_csv(var = assoc_PAC,lang = "English (American)", type = "PAC_freq_np")

```

```{r}
data<- read.csv(paste(getwd(),"/out_files/English (American)_PAC_freq_np.csv", sep = ""), as.is = T)
PAC_degree<- data$value
frequency<- data$value2
a_f<-lm(PAC_degree~ frequency)
summary(a_f)

ggplot(data , aes(x=frequency, y=PAC_degree, label=data$definition))+
  geom_text(check_overlap = F, size = 2)+
  #geom_point(alpha=1/2, position = position_jitter(h=0))+
  scale_y_continuous()+
  scale_x_continuous()+
  geom_smooth(method = "lm", se = FALSE) +
  ggtitle(label = "PAC degree ~ Frequency")
```
```{r, message=FALSE, warning=FALSE}
final_df<- read.csv(paste(getwd(),"/out_files/English (American)_PAC_freq_np.csv", sep = ""), as.is = T)
  optim(0, loglike1)$value
  optim(0, loglike0)$value
  optim(c(0,0),loglike11)$value
  optim(c(0,0),loglike01)$value
```

```{r, message=FALSE, warning=FALSE}
#data<-read.csv(paste(getwd(),"/out_files/English (American)_assoc_PAC_freq_p.csv", sep = ""), as.is = T)
source("all_helper.r")
optim_nllk(par_n = 2)
optim_par(par_n = 2)

```


```{r, message=FALSE, warning=FALSE}


dataset=data %>% mutate(n=row_number())
r=10
 ci_assoc <- vector(mode = "numeric", length = r)
 ci_freq <- vector(mode = "numeric", length = r)
  n_sample <- length(dataset[, 1])
  for (i in 1:r) {
    cur_sample <- as.data.frame(dataset$n[sample(n_sample, n_sample, replace = T)])
    colnames(cur_sample) <- "n"
    data <- cur_sample %>% left_join(dataset)
    ci_assoc[i] <- optim(0, loglike1)$par[1]
    #ci_freq[i] <- optim(c(0,0), loglike2)$par[2]
  }
  ci_assoc <- sort(ci_assoc, decreasing = F)
  len <- length(ci_assoc)
  #ci_freq <- sort(ci_freq, decreasing = F)
  
  #c(ci_assoc[as.integer(0.025 * len)+1], ci_assoc[as.integer(0.99 * len)])
  optim(0, loglike1)$value
  optim(0, loglike0)$value
  #c(ci_freq[as.integer(0.01 * len)+1], ci_freq[as.integer(0.99 * len)])
```




############################################## Polysemy
```{r}
parent_freq<- read.csv(paste(getwd(),"/in_files/parent_freq.csv", sep = ""), as.is = T) %>% mutate(freq=log(freq))
PAC_frame<- make_aoa_dataframe(lang = "English (American)") %>%
  trim_all_definition() %>%
  filter(definition %in% parent_freq$definition)

lemmalist<- PAC_frame %>% 
  filter(month==16) %>% 
  select(-uni_lemma) %>% 
  rename(uni_lemma=definition) %>% 
  select(item, uni_lemma)

assoc_pairs<- make_assoc_pairs(lemma_list = lemmalist)
assoc_PAC<- PAC_generator(vocab_month = PAC_frame, pairs = assoc_pairs) %>%
  left_join(parent_freq) %>%
  rename(value2=freq) %>%
  mutate(value2=as.numeric(value2))
 
write_out_csv(var = assoc_PAC,lang = "English (American)", type = "PAC_freq_p")

```

```{r}
data<- read.csv(paste(getwd(),"/out_files/English (American)_PAC_freq_p.csv", sep = ""), as.is = T) 
data
PAC_degree<- data$value
frequency<- data$value2
a_f<-lm(PAC_degree~ frequency)
summary(a_f)

ggplot(data , aes(x=frequency, y=PAC_degree, label=data$definition))+
  geom_text(check_overlap = F, size = 2)+
  #geom_point(alpha=1/2, position = position_jitter(h=0))+
  scale_y_continuous()+
  scale_x_continuous()+
  geom_smooth(method = "lm", se = FALSE) +
  ggtitle(label = "PAC degree ~ Frequency")
```

```{r, message=FALSE, warning=FALSE}
#data<-read.csv(paste(getwd(),"/out_files/English (American)_assoc_PAC_freq_p.csv", sep = ""), as.is = T)
source("all_helper.r")
optim_nllk(par_n = 2)
optim_par(par_n = 2)

```
```{r, message=FALSE, warning=FALSE}
dataset=data %>% mutate(n=row_number())
r=1000
 ci_assoc <- vector(mode = "numeric", length = r)
 ci_freq <- vector(mode = "numeric", length = r)
  n_sample <- length(dataset[, 1])
  for (i in 1:r) {
    print(i)
    cur_sample <- as.data.frame(dataset$n[sample(n_sample, n_sample, replace = T)])
    colnames(cur_sample) <- "n"
    data <- cur_sample %>% left_join(dataset)
    ci_assoc[i] <- optim(c(0,0),loglike_all)$par[1]
    #ci_freq[i] <- optim(c(0,0),loglike_all)$par[2]
  }
  ci_assoc <- sort(ci_assoc, decreasing = F)
  len <- length(ci_assoc)
  ci_freq <- sort(ci_freq, decreasing = F)
  
  c(ci_assoc[as.integer(0.01 * len)+1], ci_assoc[as.integer(0.99 * len)])
  c(ci_freq[as.integer(0.01 * len)+1], ci_freq[as.integer(0.99 * len)])
```



```{r}
ci_assoc[as.integer(0.025 * len)+1]
```



