```{r, message=FALSE, warning=FALSE}
source(paste(getwd(),"/helper_functions/all_helper.r",sep = ""), chdir = T)
import_all_library()
```



```{r}
library(ggthemes)
analysis<- read.csv("all_analysis.csv", as.is = T) %>% filter(!is.na(language))
analysis %>% filter(type=="phono_PAC_t1")
```

```{r}
phono_t1<- analysis %>% filter(type=="assoc_PAC_p") %>% mutate(degree_sig=ifelse(degree_sig=="NS","",degree_sig)) %>%
  mutate(degree_sig_control=ifelse(degree_sig_control=="NS","",degree_sig_control))
phono_t1

languages<- factor(rep(c("Croatian","Danish","English", "Italian", 
              "Norwegian", "Russian", "Spanish", "Turkish"),2), levels=c("Croatian","Danish","English", "Italian", 
              "Norwegian", "Russian", "Spanish", "Turkish"))
coef_degree<- c(phono_t1$degree)
coef_control<- c(phono_t1$degree_ctrl)
coefficients<- c(coef_degree, coef_control)
annotation<- c(phono_t1$degree_sig, phono_t1$degree_sig_control)
ymax<- min(coef_degree)

Model<- c(rep("Degree",8), rep("Degree|Freq+Len", 8))
mydata<- data.frame(languages, coefficients, annotation)
mydata$languages<- factor(mydata$languages,levels = c("Croatian","Danish","English", "Italian", 
              "Norwegian", "Russian", "Spanish", "Turkish"))

p <-ggplot(mydata, aes(languages,coefficients, group=type)) +
  #geom_col(stat = "identity", aes(fill = Type), position = "dodge")+
  geom_bar(stat = "identity", aes(fill = Model), position = "dodge") +
  geom_text(aes(label=annotation), position=position_dodge(0.9), vjust=-0.2, size=4.5)+
  coord_cartesian(ylim=c(ymax-0.05,0.05))+
  scale_y_reverse()+
  xlab("Languages") + ylab("Coefficients") +
  ggtitle("Associative Network") +
  #theme_few()+
  theme_classic()+
  #scale_color_solarized()+
  theme(axis.text.x = element_text(size=10, angle=45, face="bold"),
        axis.text.y = element_text(size=10, face="bold"),
        axis.title = element_text(size=14, face="bold"),
        plot.title = element_text(size=14, face="bold"),
        axis.ticks.x =element_blank(),
        legend.position = "bottom",
        axis.line.x = element_blank(),
        panel.border = element_blank())
p
```

```{r}
phono_t1<- analysis %>% filter(type=="phono_PAC_t2") %>% mutate(degree_sig=ifelse(degree_sig=="NS","",degree_sig)) %>%
  mutate(degree_sig_control=ifelse(degree_sig_control=="NS","",degree_sig_control))
phono_t1
languages<- c("Croatian","Danish","English", "Italian", 
              "Norwegian", "Russian", "Spanish", "Turkish")
coef_degree<- c(phono_t1$degree)
coefficients<- c(coef_degree)
annotation<- c(phono_t1$degree_sig)


Type<- c("Coef_Degree",8)
mydata<- data.frame(languages, coefficients, annotation)
mydata$languages<- factor(mydata$languages,levels = c("Croatian","Danish","English", "Italian", 
              "Norwegian", "Russian", "Spanish", "Turkish"))

p <-ggplot(mydata, aes(languages,coefficients)) +
  #geom_col(stat = "identity", aes(fill = Type), position = "dodge")+
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(limits = c(0,-0.6))+
  scale_y_reverse()+
  geom_text(aes(label=annotation), position=position_dodge(0.9), vjust=-0.2, size=4.5)+
  xlab("Languages") + ylab("Coefficients") +
  ggtitle("Phonological Network (T<=2)") +
  theme(axis.text.x = element_text(size=10, angle=45),
        axis.title = element_text(size=14, face="bold"),
        plot.title = element_text(size=14, face="bold"))+
  theme_bw()
p
```



```{r}
parent_freq<- read.csv(paste(getwd(),"/in_files/log_freq.csv",sep = ""), as.is = T) 
phono_pat<- read.csv(paste(getwd(),"/out_files/", "English (American)_phono_PAC_t2.csv", sep = ""), as.is = T) %>%
  left_join(parent_freq) %>%
  rename(value2=freq) %>%
  mutate(value2=ifelse(is.na(value2), 0, value2))
phono_pat
```

```{r, message=FALSE, warning=FALSE}
source(paste(getwd(),"/helper_functions/all_helper.r",sep = ""), chdir = T)
import_all_library()
phono_pat<- read.csv(paste(getwd(),"/out_files/", "English (American)_phono_PAC_t2.csv", sep = ""), as.is = T) %>%
    rowwise() %>%
    mutate(IPA=Speak(lang = "English (American)", word = definition)) %>%
    trim_IPA_completely() %>%
    mutate(value2=str_count(IPA))
phono_pat
```

```{r}
final_df<<- phono_pat %>% ungroup()
final_df
optim_nllk(2)
```

```{r}
parent_freq<- read.csv(paste(getwd(),"/in_files/log_freq.csv",sep = ""), as.is = T) 
df<- final_df %>% filter(learned==1) %>% left_join(parent_freq) %>% mutate(freq=ifelse(is.na(freq),0,freq))
degree<- df$value
length<- df$value2
freq<- df$freq
month<- df$month

m_f<- lm(month ~ freq)
summary(m_f)

m_fl<- lm(month ~ freq+length)
summary(m_fl)

m_d<- lm(month ~ degree)
summary(m_d)

m_dl<- lm(month ~ degree+length)
summary(m_dl)

m_df<- lm(month ~ degree+ freq)
summary(m_df)

m_dlf<- lm(month ~ degree +length+freq)
summary(m_dlf)

lrtest(m_f, m_df)

  # ggplot(df , aes(x=month, y=degree))+
  # #geom_text(check_overlap = F, size = 2, angle=45)+
  # geom_point(alpha=1/2, position = position_jitter(h=0))+
  # #facet_wrap(~value2)+
  # scale_y_continuous()+
  # scale_x_continuous(breaks = seq(16,30, by=1))+
  # geom_smooth(method = "lm", se = FALSE) +
  # ggtitle(label = "Phonological degree ~ Month (Length Controled)")
```

```{r}
source(paste(getwd(),"/helper_functions/all_helper.r",sep = ""), chdir = T)
import_all_library()

```
```{r}

languages<-c("Danish","English (American)", "Italian", "Norwegian", "Russian","Spanish","Turkish", "Croatian","Slovak","German")
types<-c("phono_PAC")
thresholds<-c(1,2)
phono_df<- data.frame(matrix(ncol = 5, nrow = 500))
colnames(phono_df)<- c("language", "type","only_degree","degree_after_ctrl","lrtest")
i=1
for (language in languages) {
  for (type in types) {
    for (threshold in thresholds){
      print(c(language, type, threshold))
      ret<- significance_testing(lang = language,
                                  type = type,
                                  threshold = threshold)
      #phono_df[i,]<- ret
      i=i+1
    }
  }
}

#phono_df
#write.csv(phono_df, file = "phono_coefficients.csv", row.names = F)
```

```{r}
#"Danish","English (American)", "Italian") "Russian","Norwegian",
languages<-c("Turkish","Croatian")#,"Russian","Norwegian") #,"Slovak","German")
types<-c("phono_PAC_t2")
cor_df<- data.frame(matrix(ncol = 7, nrow = 500))
colnames(cor_df)<- c("language", "type","degree", "degree_sig","degree_ctrl", "degree_sig_control","lrtest")
i=1
for (language in languages) {
  for (type in types) {
    print(c(language,type))
      ret<- significance_testing(lang = language,
                                  type = type,
                                  threshold = 0)
      cor_df[i,]<- ret
      i=i+1
      
  }
}

#cor_df
#write.csv(cor_df, file = "assocMcRae_coefficients.csv",row.names = F)
```
```{r}
    lang_name<<- "Norwegian"
    # age of acquisition data frame
    aoa_frame<- make_aoa_dataframe(lang = lang_name)
    # list of lemmas of learnt words
    first_month<- aoa_frame$month[1]
    lemma_list<- aoa_frame %>%
      trim_all_unilemma() %>%
      filter(month==first_month) %>%
      select(item, uni_lemma) 
    # list of definitions of learnt words
    def_list<- aoa_frame %>%
      trim_all_definition() %>% 
      filter(month==first_month) %>%
      select(item, definition)
    lemma_list
    def_list
```
```{r}
def_list %>% filter(def_list$item %in% lemma_list$item)
```


```{r}

languages<-c("Danish","English (American)", "Italian", "Norwegian", "Russian","Spanish","Turkish","Croatian")
types<-c("assoc_PAC_p")
cor_df<- data.frame(matrix(ncol = 3, nrow = 500))
colnames(cor_df)<- c("language", "threshold","correlation")
i=1
for (language in languages) {
  for (type in types) {
      print(c(language, type))
      cors<- significance_testing(lang = language,
                                  type = type,
                                  threshold = 0)
      
      i=i+1
  }
}


```
```{r}
lang="English (American)"
  parent_freq<- read.csv(paste(getwd(),"/in_files/log_freq.csv",sep = ""), as.is = T) 
  df<- read.csv(paste(getwd(),"/out_files/English (American)_phono_PAC_t2.csv", sep = ""), as.is = T) %>%
    trim_all_definition() %>%
    rowwise() %>%
    mutate(IPA=Speak(lang = lang, word = definition)) %>%
    trim_IPA_completely() %>%
    mutate(value2=str_count(IPA)) %>%
    ungroup() %>% 
    left_join(parent_freq) %>% 
    mutate(freq=ifelse(is.na(freq),0,freq)) %>% #if can't find the freq of word, set it to 0
    rename(value3=freq) 

```

```{r, message=FALSE, warning=FALSE}
final_df<<-df
optim(0,loglike1)$value
optim(0,loglike0)$value
optim(c(0,0,0),loglike011)$value
optim(c(0,0,0),loglike111)$value
#optim(0,loglike1)
optim_nllk(par_n = 2)
```
```{r}
graph_df<- df %>% filter(learned==1) %>% mutate(ortho=str_count(definition))
graph_df
month<- graph_df$month
length<- graph_df$value2
freq<- graph_df$value3
ortho<-graph_df$ortho
summary(lm(month ~length))
summary(lm(month ~ortho))
ggplot(graph_df , aes(x=length, y=month, label=graph_df$definition))+
  geom_text(size=2, position = position_jitter(h=0.5))+
  #geom_point(alpha=1/2, position = position_jitter(h=0))+
  scale_y_continuous(breaks = seq(16,30, by=1))+
  scale_x_continuous(breaks = seq(1,15, by=1))+
  geom_smooth(method = "lm", se = FALSE)

```
```{r}
lang="Russian"
file_name="Russian_assoc_PAC_p"
  parent_freq<- read.csv(paste(getwd(),"/in_files/log_freq.csv",sep = ""), as.is = T) 
  df<- read.csv(paste(getwd(),"/out_files/", file_name,".csv", sep = ""), as.is = T) %>%
    trim_all_definition() %>%
    trim_all_unilemma() %>%
    rowwise() %>%
    mutate(IPA=Speak(lang = lang, word = definition)) %>%
    trim_IPA_completely() %>%
    mutate(value2=str_count(IPA)) %>%
    ungroup() %>% 
    filter(learned==1) %>% 
    left_join(parent_freq) %>% 
    mutate(freq=ifelse(is.na(freq),0,freq)) #if can't find the freq of word, set it to 0
df
```
```{r}
file_name<- "Russian_assoc_PAC_np"
lang="Russian"
  parent_freq<- read.csv(paste(getwd(),"/in_files/log_freq.csv",sep = ""), as.is = T) 
  df<- read.csv(paste(getwd(),"/out_files/", file_name,".csv", sep = ""), as.is = T) %>%
    trim_all_definition() %>%
    trim_all_unilemma() %>%
    rowwise() %>%
    mutate(IPA=Speak(lang = lang, word = definition)) %>%
    trim_IPA_completely() %>%
    mutate(value2=str_count(IPA)) %>%
    ungroup() %>% 
    filter(learned==1) %>% 
    left_join(parent_freq) %>% 
    mutate(freq=ifelse(is.na(freq),0,freq)) #if can't find the freq of word, set it to 0
  
```
```{r}
df
```

```{r}
  degree<- df$value
  length<- df$value2
  freq<- df$freq
  month<- df$month
  m_d<- lm(month ~ degree)
  m_fl<- lm(month ~ freq+length)
  m_dlf<- lm(month ~ length+freq+degree)
summary(m_d)$coefficients
print(summary(m_dlf))
print(lrtest(m_fl, m_dlf))
```

```{r}
type="assoc_PAC"
c(lang,type, summary(m_d)$coefficients[2,1],summary(m_dlf)$coefficients[4,1],lrtest(m_fl, m_dlf)[2,5])

```
```{r}
item_data<- get_lang_item_data(lang = "English (American)")
instr_data<- get_lang_instr_data(lang = "English (American)")
admin_data<- get_lang_admin_data(lang = "English (American)")

```
```{r}
item_data
instr_data
admin_data
get_lang_aoa(item_data = item_data,admin_data = admin_data,instr_data = ,instr_data)
#get_lang_aoa(item_data = item_data, instr_data = instr_data, admin_data = admin_data)
```
```{r}
word_aoa
  ages<- get_nwords_by_age(word_aoa)
  df <- data.frame()
  for (i in ages) {
    rem_words <- word_aoa %>% filter(age >= i)
    rem_lemma <- c(rem_words$uni_lemma)
    rem_def <- c(rem_words$definition)
    rem_item<- c(rem_words$item)
    corr_age <- rep(i, times = length(rem_lemma))
    curr_df <- data.frame(corr_age, rem_item, rem_lemma, rem_def)
    df <- rbind(df, curr_df)
  }  
  df <- df %>% rename(uni_lemma = rem_lemma, definition=rem_def, item=rem_item)%>%
    left_join(word_aoa %>% select(item, age)) %>%
    mutate(learned = as.numeric(age == corr_age)) %>%
    select(corr_age, item, definition, uni_lemma,learned) %>%
    rename(age = corr_age) %>%
    arrange(age, item)
  return(df)
```
```{r}
word_aoa<- get_lang_aoa(item_data = item_data,admin_data = admin_data,instr_data = ,instr_data)
word_aoa
get_nwords_by_age(word_aoa)
```
```{r}
aoa<- make_aoa_dataframe("English (American)")
aoa
lemma<- aoa %>% filter(age==16) %>% select(item, uni_lemma)
lemma
```
```{r}
pairs<- make_assoc_pairs(lemma_list = lemma)
```
```{r}
PAC_generator(vocab_age = aoa, word_pairs = pairs)
```

