```{r}
source(paste(getwd(),"/helper_functions/all_helper.r",sep = ""), chdir = T)
import_all_library()
```


```{r, message=FALSE, warning=FALSE}
item_data<- get_lang_item_data(lang = "English (American)")

McRae_feature<- make_McRae_pairs(words_list = item_data) %>% McRae_threshold(threshold = 1)

aoa_frame<- make_aoa_dataframe(lang = "English (American)")

McRae_PAC<- PAC_generator(vocab_month = aoa_frame, pairs = McRae_feature)
McRae_PAT<- PAT_generator(vocab_month = aoa_frame, semantic_feature = McRae_feature)
```

```{r, message=FALSE, warning=FALSE}
write.csv(McRae_PAC, file = "English_M_PAC.csv", row.names = F)
#write.csv(McRae_PAT, file = "English_M_PAT.csv", row.names = F)
data<- read.csv("English_M_PAC.csv", as.is = T)
 optim(0, loglike)
 optim(0, loglike0)
```



```{r}
lemma_list<- McRae_PAC %>% filter(month==16) %>% select(item, definition) %>% rename(uni_lemma=definition)
lemma_list

assoc_pairs<- make_assoc_pairs(lemma_list = lemma_list)
assoc_pairs
assoc_PAC<- PAC_generator(vocab_month = aoa_frame,pairs = assoc_pairs)
assoc_PAC 
```


```{r, message=FALSE, warning=FALSE}
write.csv(assoc_PAC, file = "English_assoc_PAC_np.csv", row.names = F)
data<- read.csv("English_assoc_PAC_np.csv", as.is = T)
optim(0, loglike)
optim(0, loglike0)
```

```{r, message=FALSE, warning=FALSE}
assoc_PAT<- PAT_generator(vocab_month = aoa_frame %>% filter(item %in% lemma_list$item), semantic_feature = assoc_pairs)
assoc_PAT
write.csv(assoc_PAT, file = "English_assoc_PAT.csv", row.names = F)
data<- read.csv("English_assoc_PAT.csv", as.is = T)
optim(0, loglike)
optim(0, loglike0)
```

```{r}
parent_freq<- read.csv(paste(getwd(),"/in_files/log_freq.csv", sep = ""), as.is = T)
assoc_PAC_freq<- assoc_PAC %>%
  left_join(parent_freq) %>%
  rename(value2=freq)

assoc_PAC_freq
write_out_csv(var = assoc_PAC_freq,lang = "English (American)", type = "PAC120_freq_np")

```

```{r}
data<-read.csv(paste(getwd(),"/out_files/English (American)_PAC120_freq_np.csv", sep = ""), as.is = T)
source("all_helper.r")
optim_nllk(par_n = 2)
optim_par(par_n = 2)
```

###################################






```{r, message=FALSE, warning=FALSE}
item_data<- get_lang_item_data(lang = "English (American)") %>% 
  trim_all_definition() %>% 
  trim_all_unilemma()

McRae_feature<- get_McRae(words_list = item_data) %>% McRae_threshold(threshold = 1)

aoa_frame<- make_aoa_dataframe(lang = "English (American)") %>% 
  trim_all_definition() %>% 
  trim_all_unilemma()

McRae_PAC<- PAC_generator(vocab_month = aoa_frame, pairs = McRae_feature)
McRae_PAT<- PAT_generator(vocab_month = aoa_frame, semantic_feature = McRae_feature)
McRae_PAC
```


```{r, message=FALSE, warning=FALSE}
# write.csv(McRae_PAC, file = "English_M_PAC_p.csv", row.names = F)
# write.csv(McRae_PAT, file = "English_M_PAT_p.csv", row.names = F)
data<- read.csv("English_M_PAT_p.csv", as.is = T)
 optim(0, loglike)
 optim(0, loglike0)
```

```{r}
lemma_list<- McRae_PAC %>% filter(month==16) %>% 
  select(item, definition) %>% 
  rename(uni_lemma=definition) %>% 
  trim_all_unilemma()
lemma_list
assoc_pairs<- make_assoc_pairs(lemma_list = lemma_list)

assoc_PAC<- PAC_generator(vocab_month = aoa_frame,pairs = assoc_pairs)
assoc_PAC 
```

```{r, message=FALSE, warning=FALSE}
write.csv(assoc_PAC, file = "English_assoc_PAC120_p.csv", row.names = F)
data<- read.csv("English_assoc_PAC120_p.csv", as.is = T)
optim(0, loglike)
optim(0, loglike0)
```


```{r, message=FALSE, warning=FALSE}
assoc_PAT<- PAT_generator(vocab_month = aoa_frame %>% filter(item %in% lemma_list$item), semantic_feature = assoc_pairs)
assoc_PAT
write.csv(assoc_PAT, file = "English_assoc_PAT120_p.csv", row.names = F)
data<- read.csv("English_assoc_PAT120_p.csv", as.is = T)
optim(0, loglike)
optim(0, loglike0)
```

```{r}
parent_freq<- read.csv(paste(getwd(),"/in_files/log_freq.csv", sep = ""), as.is = T)
assoc_PAC_freq<- assoc_PAC %>%
  left_join(parent_freq) %>%
  rename(value2=freq)

assoc_PAC_freq
write_out_csv(var = assoc_PAC_freq,lang = "English (American)", type = "PAC120_freq_p")

```

```{r, message=FALSE, warning=FALSE}
source("all_helper.r")
data<-read.csv(paste(getwd(),"/out_files/English (American)_PAC120_freq_p.csv", sep = ""), as.is = T)
data
optim_nllk(par_n = 2)
optim_par(par_n = 2)
optim(0, loglike)
optim(0, loglike0)
```