```{r}
langs<- c("English (American)", "Spanish", "Croatian", "Italian", "Danish", "Norwegian", "Turkish")
abbr <- c("en-us", "es", "hr", "it", "da", "no", "tr")
#for (lang in langs){
lang="English (American)"
  lang_abbr<- abbr[which(langs==lang)]
  IPA_items<- get_lang_item_data(lang = lang, lang_form = "WS", lex_class = "nouns") %>% 
    select(item, definition, uni_lemma) %>%
    #trim_all_definition() %>% 
    rowwise() %>%
    mutate(IPA= Speak(lang=lang, word=definition))

  item_IPA_join <- IPA_items %>% select(item, IPA)
  only_IPA <- IPA_items %>% select(IPA)
  item_IPA_join
  only_IPA
  IPA_pairs <- expand.grid(only_IPA$IPA, only_IPA$IPA) %>%
    left_join(item_IPA_join, by = c("Var1" = "IPA"))  %>%
    rename(pair = item, pair.definition = Var1) %>%
    left_join(item_IPA_join, by = c("Var2" = "IPA")) %>%
    rename(item.definition = Var2) %>%
    rowwise() %>%
    mutate(dist = adist(item.definition, pair.definition)) %>%
    select(item, item.definition, pair, pair.definition, dist)
  
#  aoa_frame<- make_aoa_dataframe(lang = "English")
#  phono_PAC<- PAC_generator(vocab_month = aoa_frame, pairs = IPA_pairs %>% rename(link=dist))
#  write_out_csv(var = IPA_items, lang = lang, type = "IPA")
#}
IPA_pairs
```

```{r}
aoa_frame<- make_aoa_dataframe(lang = lang) %>% filter(definition %in% parent_freq$definition)


IPA_pairs_thresholded<- IPA_pairs %>% mutate(link=as.numeric(dist<=2)) %>% filter(item!=pair) 
phono_PAC<- PAC_generator_phono(vocab_month = aoa_frame, pairs = IPA_pairs_thresholded)
phono_PAC

assoc_PAC<- phono_PAC %>% 
   #add_polysemy_value() %>%
   rowwise() %>%
   mutate(IPA=Speak(lang =lang,word = definition))

```

