---
title: "Untitled"
author: "me"
date: "6/8/2017"
output: html_document
---
Libraries

```{r}
geom_text
geom_label
ggrepel

```

```{r, message=FALSE, warning=FALSE}
source("all_helper.r")
import_all_library()



```
`

```{r}
just_PAC<-PAC_generator(vocab_month = PAC_frame, pairs = assoc_pairs)
```

```{r}
data<- read.csv(paste(getwd(),"/out_files/English (American)_PAC_freq_less.csv", sep = ""), as.is = T)
PAC_degree<- data$value
frequency<- data$value2
a_f<-lm(PAC_degree~ frequency)
summary(a_f)

ggplot(data, aes(x=frequency, y=PAC_degree, label=data$definition))+
  geom_text(check_overlap = F, size = 4)+
  #geom_point(alpha=1/2, position = position_jitter(h=0))+
  scale_y_continuous()+
  scale_x_continuous()+
  geom_smooth(method = "lm", se = FALSE) +
  ggtitle(label = "PAC degree ~ Frequency")
```


```{r}
write_out_csv(var = assoc_PAC, lang = "English (American)", type = "assoc_PAC")
data<- read.csv(paste(getwd(),"/out_files/English (American)_assoc_PAC.csv", sep = ""), as.is = T) %>% select(-value) %>% rename(value=value2)
  
data
```


#Optimization
```{r}
# This is the loglikelihood function we're trying to MINIMIZE
# loglike <- function(beta){
# #beta=0
#   
#   # calculate numerator
#   learned_words<- data %>%
#     filter(learned==1) %>%
#     mutate(numerator=exp(value*beta)) %>%
#     select(month, numerator)
#   
# # calculate denumerator
#   all_words<- data %>%
#     group_by(month) %>%
#     summarise(denominator=sum(exp(value*beta))) %>%
#     select(month, denominator)
#   
# # calculate the return value
#   ret<- learned_words %>%
#     left_join(all_words) %>%
#     summarise(nLLK=sum(log(numerator/denominator)))
# 
#   return(-ret$nLLK)
#   
# }

#```

#```{r}
#This is the optim with parameter beta. We're trying to MINIMIZE the value of loglike function. It does not show the confidence interval
# This code block works
optim_param <- function() {
  optim_stat <- optim(0, loglike)
  return(optim_stat)
}
#optim_param()

``` 
```{r}
#data<- read.csv(paste(getwd(),"/out_files/English (American)_assoc_PAC_wotrim.csv", sep = ""), as.is = T)
#data<- read.csv(paste(getwd(),"/out_files/English (American)_freq.csv", sep = ""), as.is = T) %>% mutate(value= as.numeric(value))
optim(0, loglike)
  
#  mutate(value= if_else(grepl(" \\(animal\\)",uni_lemma),gsub(" \\(animal\\)","", uni_lemma),uni_lemma)) %>% 
#  mutate(value= gsub("[*]","", uni_lemma))

```


```{r, message=FALSE, warning=FALSE}

dataset=data %>% mutate(n=row_number())
r=1000
 confint <- vector(mode = "numeric", length = r)
  n_sample <- length(dataset[, 1])
  for (i in 1:r) {
    cur_sample <- as.data.frame(dataset$n[sample(n_sample, n_sample, replace = T)])
    colnames(cur_sample) <- "n"
    data <- cur_sample %>% left_join(dataset)
    confint[i] <- optim(0, loglike)$par
  }
  ci <- sort(confint, decreasing = F)
  len <- length(ci)

  c(ci[as.integer(0.01 * len)+1], ci[as.integer(0.99 * len)])

```


```{r}
confint <- vector(mode = "numeric", length = r)
confint[1]<- 1
confint
c(ci[as.integer(0.01 * len)+1], ci[as.integer(0.99 * len)])
```

# ```{r}
# param_ci<- boot(data= data, statistic = optim_param, R=2000)
# ```
```{r, message=FALSE, warning=FALSE}
param_confint(dataset = all_data, r=10)
```

```{r}
get_item_data(language = "English", form = "WS")
```



